name: ot
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  http:
  flutter_svg: ^0.17.4
  fluttertoast: ^4.0.0
  toast:
  flutter_tindercard: ^0.1.8
  image_picker:
  stream_chat_flutter:
  datetime_picker_formfield: ^0.1.8
  custom_navigator:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"
  flutter_launcher_name: "^0.0.1"

flutter_icons:
  andriod: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_launcher_name:
  name: "OTA"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - Images/OTA.png
    - Images/profile1.jpg
    - Images/profile2.jpg
    - Images/profile3.jpg
    - Images/profile4.jpg
    - Images/profile5.jpg
    - Images/placeholder-image.png